name: goreleaser

on:
  push:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Go
        run: actions/setup-go@v1.0.0
      -
         name: Download sdk
         run: go get github.com/peacemakr-io/peacemakr-go-sdk
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
